# Traduccion por Usuario Telegram @jesymca @ContactoConJE_bot
dict = {
    "grp_warn_no_reason": "❗️️ {} ha sido advertido [{}/{}].",
    "grp_warn_reason": "❗️️ {} ha sido advertido [{}/{}] para <b>{}</b>",
    "log_warn_reason": "❗️ <b>Advertir</b> \ nTo: {}\nBy: {}\ nReason: {}\nUser advierte ahora: {}/{}",
    "log_warn_no_reason": "❗️ <b>Advertir</b>\nTo {}\nBy: {}\nUser advierte ahora: {}/{}",
    "log_new_user": "➕ <b>Nuevo usuario</b>\ n-> {}",
    "log_new_user_closed": "➕ <b>Nuevo usuario</b>\ n-> {}\nThe grupo estaba cerrado, lo pateé.",
    "grp_ban_reason": "🚷 {} ha sido prohibido para {}.",
    "log_ban_reason": "🚷 <b>Prohibir</b>\nTo {}\nBy: {}\ nReason: {}",
    "grp_ban_no_reason": "🚷 {} ha sido prohibido.",
    "log_ban_no_reason": "🚷 <b>Prohibir</b>\nTo {}\nBy: {}",
    "grp_mute_custom": "🔇 {} se ha silenciado durante {} horas.",
    "log_mute_custom": "🔇 <b>Silenciar</b>\nTo {}\nBy: {}\ nHoras: {}",
    "grp_mute_default": "🔇 {} se ha silenciado durante <b>{}</b>hasta la próxima hora.",
    "log_mute_default": "🔇 <b>Silenciar</b>\nTo {}\nBy: {}\ nReason: {}\ nHoras: 1",
    "grp_kick_reason": "❕ {} ha sido expulsado para <b>{}</b>.",
    "log_kick_reason": "❕ <b>Patada</b>\nTo {}\nBy: {}\ nReason: {}",
    "grp_kick_no_reason": "❕ {} ha sido pateado.",
    "log_kick_no_reason": "❕ <b>Patada</b>\nTo {}\nBy: {}",
    "grp_unban": "✅ {} desbloqueado.",
    "log_unban": "✅ <b>Anular la prohibición</b>\nTo {}\nBy: {}",
    "grp_unwarn": "❎ {} sin advertencia. \nNow tiene {} advertencias.",
    "log_unwarn": "❎ <b>No advertir</b>\nTo {}\nBy: {}\nUser advierte ahora: {}/{}",
    "grp_unmute": "🔊 {} desactivado.",
    "log_unmute": "🔊 <b>Activar sonido</b>\nTo {}\nBy: {}",
    "grp_info": "🙍‍♂️ <b>Información de usuario</b>\ nUser: {}\ nChatID: <code> {} </code> \ nWarns: {}",
    "grp_new_helper": "⛑ {} ahora es <b>Helper</b>.",
    "log_new_helper": "⛑ <b>Nuevo ayudante</b>\nTo {}\nBy: {}",
    "grp_rem_helper": "⛑ {} eliminado de <b>Ayudantes</b>.",
    "log_rem_helper": "⛑ <b>Asistente eliminado</b>\nTo {}\nBy: {}",
    "grp_new_moderator": "👷🏻 {} ahora es <b>Moderador</b>.",
    "log_new_moderator": "👷🏻 <b>Nuevo moderador</b>\nTo {}\nBy: {}",
    "grp_rem_moderator": "👷🏻 {} eliminado de <b>Moderadores</b>.",
    "log_rem_moderator": "👷🏻 <b>Moderador eliminado</b>\nTo {}\nBy: {}",
    "grp_new_manager": "🛃 {} ahora es <b>Administrador</b>.",
    "log_new_manager": "🛃 <b>Nuevo administrador</b>\nTo {}\nBy: {}",
    "grp_rem_manager": "🛃 {} eliminado de <b>Administradores</b>.",
    "log_rem_manager": "🛃 <b>Administrador eliminado</b>\nTo {}\nBy: {}",
    "bot_reload": "✅ <b>¡Bot recargado!</b>\nBy: {}",
    "bot_start_inactive_kick": "☢️ <b>Patada de usuarios inactivos</b>\ nIniciado por: {}\nMax. Días inactivos: {}",
    "bot_end_inactive_kick": "☢️ <b>¡Kick de usuarios inactivos finalizado!</b>",
    "str_max_warns": "Se superó el máximo de advertencias",
    "grp_staff_call": "🆘 <i>Llamada recibida.</i>",
    "log_staff_call_reply": "🆘 <b>Llamada del personal</b>\nBy: {}\nTo {}\nMessage: {}",
    "log_staff_call_noreply": "🆘 <b>Llamada del personal</b>\nBy: {}\nMessage: {}",
    "grp_staff_title": "🔰️ <b>PERSONAL DEL GRUPO</b>🔰️",
    "grp_staff_founder": "\n\n  👑 <b>Fundador</b>",
    "grp_staff_admins": "\n\n  👮🏼 <b>Administradores</b>",
    "grp_staff_moderators": "\n\n  👷🏻 <b>Moderadores</b>",
    "grp_staff_managers": "\n\n  🛃 <b>Administradores</b>",
    "grp_staff_helpers": "\n\n  ⛑ <b>Ayudantes</b>",
    "grp_set_username": "🌐 {}, por favor, establezca un <b>nombre de usuario</b>en la configuración de Telegram",
    "grp_scan_file": "<i>Escaneando archivo ...</i>",
    "grp_scanned_safe": "✅ Análisis de archivos: Safe\nAlert {}/{}",
    "grp_scanned_warning": "⚠️ Análisis de archivos: Advertencia\nAlert {}/{}",
    "grp_scanned_malware": "🛑️ Análisis de archivos: Malware\nAlert {}/{}",
    "grp_shorter_name": "🌐 {}, por favor, establezca un <b>nombre más corto</b>en la configuración de Telegram.",
    "log_blacklist_word": "🆎 <b>Palabra incluida en la lista negra</b>\nBy: {}",
    "str_forward": "Reenvío desde un canal no incluido en la lista blanca",
    "str_porn": "Medios porno",
    "str_offensive": "Medios ofensivos",
    "grp_global_silence_on": "🔇 <b>¡Silencio global activado!</b>\nNow, solo el personal del grupo puede escribir mensajes.",
    "log_global_silence_on": "🔇 <b>Silencio global activado</b>\nBy: {}",
    "grp_global_silence_off": "🔊 <b>¡Silencio global desactivado!</b>\nNow, todos los usuarios pueden escribir mensajes.",
    "log_global_silence_off": "🔊 <b>Global Silence Off</b>\nBy: {}",
    "grp_closegroup": "🚷 <b>¡Grupo cerrado!</b>\nNow, nadie puede ingresar a este grupo.",
    "log_closegroup": "🚷 <b>Grupo cerrado</b>\nBy: {}",
    "grp_opengroup": "✅ <b>¡Grupo abierto!</b>\nNow, todos pueden ingresar a este grupo.",
    "log_opengroup": "✅ <b>Grupo abierto</b>\nBy: {} ",
    "cmd_helper": "/helper",
    "cmd_unhelper": "/unhelper",
    "cmd_mod": "/mod",
    "cmd_unmod": "/unmod",
    "cmd_manager": "/administrador",
    "cmd_unmanager": "/unmanager",
    "cmd_tell": "/tell",
    "cmd_reload": "/reload",
    "cmd_kickinactive": "/kickinactive",
    "cmd_warn": "/advertir",
    "cmd_delwarn": "/delwarn",
    "cmd_mute": "/mute",
    "cmd_kick": "/kick",
    "cmd_ban": "/ban",
    "cmd_unban": "/unban",
    "cmd_unwarn": "/unwarn",
    "cmd_unmute": "/unmute",
    "cmd_info": "/info",
    "cmd_silenceon": "/silenton",
    "cmd_silenceoff": "/silentoff",
    "cmd_del": "/del",
    "cmd_staff": "/personal",
    "cmd_rules": "/reglas",
    "cmd_pin": "/pin",
    "cmd_unpin": "/desanclar",
    "cmd_closegroup": "/closegroup",
    "cmd_opengroup": "/opengroup"
}
